version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nginx-app
    networks: 
      - node-network 
    ports:  
      - "88:80"
      
  app:
    build:
      context: nodejs
    container_name: app  
    entrypoint: ./wait-for-it.sh -h db -p 3306 --strict --timeout=5 -- docker-entrypoint.sh    
    command: node index.js
    networks: 
      - node-network
    volumes: 
      - ./nodejs:/usr/src/app    
    tty: true  
    ports:
      - "8000:3000"
    depends_on: 
      - db  

  db:
    image: hypriot/rpi-mysql 
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root  
    networks: 
      - node-network  

networks:
  node-network:
    driver: bridge      
